### ISSUE TITLE
收藏列表加载失败

### ISSUE THREAD

**Issue by 666liuzi** [niuhuan/kobi#1]
无法正常显示账户收藏列表，希望大佬解决

**Comment by niuhuan** [comment]
解决了？

**Comment by 666liuzi** [comment]
使用原来的账号还是不能加载收藏夹，但是在kobi内新注册的账号可以正常使用。我就是新创建了一个账号。
同时发现打开漫画详情页时偶尔会出现加载失败，不过次数很少，而且只要重新点开就可以，不影响使用。
软件很好用，希望佬能继续完善



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月29日(周三) 上午6:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [niuhuan/kobi] 收藏列表加载失败 (Issue #1)




 
解决了？
