### ISSUE TITLE
Android的数据保存位置

### ISSUE THREAD

**Issue by lilywonka** [niuhuan/kobi#10]
首先感谢开发者大大，华为手机测试加载漫画速度相比原版大大加快，但是下载经常中断，不知道是和服务器还是其他因素有关。
还有想请问开发者大大，安卓的数据保存位置在哪个目录下？下载下来的漫画是.copy格式还是.jpg或者其他格式呢？因为有些喜欢的漫画想自制移到kindle上看，所以有此提问。
0.0.9版本 华为mate30
谢谢

**Comment by niuhuan** [comment]
是.jpg去掉拓展名,并且需要root权限才能查看到,导出到SDCard或者手机内存或者电脑硬盘的功能还在在中。
