### ISSUE TITLE
使用rust真的有性能提升吗？

### ISSUE THREAD

**Issue by Minori-ty** [niuhuan/kobi#13]
dart本身的性能也挺好的，为什么不全用dart来做网络请求？毕竟dart调用rust，会有几百毫秒的时间损耗

**Comment by niuhuan** [comment]
性能并没有说的那么差，性能的损失几毫秒或者几乎没有感觉。

flutter请求网络一样会使用isolate发生多余的内存拷贝、好在ram的读写是非常快的

我个人无法忍受flutter的数据库框架。文件读写。线程管理。且flutter的线程会在后台被挂起。一般很少用flutter部分实现这些。

更多的原因可以看flutter_rust_bridge中why flutter + rust 部分

**Comment by Minori-ty** [comment]
> 性能并没有说的那么差，性能的损失几毫秒或者几乎没有感觉。
> 
> flutter请求网络一样会使用isolate发生多余的内存拷贝、好在ram的读写是非常快的
> 
> 我个人无法忍受flutter的数据库框架。文件读写。线程管理。且flutter的线程会在后台被挂起。一般很少用flutter部分实现这些。
> 
> 更多的原因可以看flutter_rust_bridge中why flutter + rust 部分

那请问flutter+golang呢？

**Comment by niuhuan** [comment]
一样的道理，喜欢用哪个用哪个嘛。

**Comment by Minori-ty** [comment]
> 一样的道理，喜欢用哪个用哪个嘛。

好的，谢谢指教
