### ISSUE TITLE
登录和连接失败

### ISSUE THREAD

**Issue by AriaArcadia** [niuhuan/kobi#18]
使用环境：校园网+移动（江西）数据网络，移动（海南）数据网络

设备：Windows11专业版 客户端/Android Coloros11

不能使用，刷新漫画界面提示加载失败，登录界面提示“请更新到最新的客户端”。合理怀疑是Copy官方升级改了接口

**Comment by AriaArcadia** [comment]
又看了下官方客户端和接口，也可能是2.1.7被废弃了（按说我fork完改一下版本号就行了怎么编译过不去啊

**Comment by niuhuan** [comment]
您需要安装最新版rust-lang、以及flutter-sdk

**Comment by niuhuan** [comment]
很欢迎您的pr的、可以在群里问我或者贴图给我、很乐意解决您无法编译的问题

**Comment by AriaArcadia** [comment]
没有pr和本地环境，用github action跑的package和release两个编译过程。
暂时没法配环境，只能等您修复了，感谢

**Comment by niuhuan** [comment]
看了一下您的环境，安卓没成功只是没配环境变量，签名的jks的base64和密码
