### ISSUE TITLE
iPad上无法安装软件

### ISSUE THREAD

**Issue by userA95** [niuhuan/kobi#21]
把所有的都下载了一遍但是没有能自动安装的，改后缀也无法安装，请问该怎么办？

**Comment by niuhuan** [comment]
1. 您需要自行签名服务才能在苹果设备使用
2. iPad应该使用ipa安装包
3. "安装开源ios应用"," 为什么需要签名"等问题可以在苹果官方网站发送工单咨询客服。

同时您可以在这购买签名
https://t.me/+7EyAiARvtENkMTU1
