### ISSUE TITLE
Kobi漫画下载问题

### ISSUE THREAD

**Issue by 1395771519** [niuhuan/kobi#5]
每次下载单行本后，打开阅读发现都是后半部分的顺序错乱，单独下载一话没试过，不确定会不会有同样问题(我是在没有登录状态下载的漫画，安装的版本0.0.8，但是手机打开看版本显示0.0.1
![Screenshot_2023-12-29-22-40-50-682_com miui securitycenter](https://github.com/niuhuan/kobi/assets/59351770/eecbc0f2-e563-4f55-8ade-73f5e198e0fc)
)[
![Screenshot_2023-12-29-22-49-14-983_opensource kobi](https://github.com/niuhuan/kobi/assets/59351770/8ad58892-8ec5-41bf-a00a-ddff57eca2d6)
](url)

**Comment by niuhuan** [comment]
版本是没有问题的，不打算更新安装包上的版本，为了能前后版本覆盖安装，也许是因为没有对下载的内容进行排序。还需要优化

**Comment by niuhuan** [comment]
您下载的单行本的名字是什么，我可以试一下

**Comment by 1395771519** [comment]
后面试了一下，无论是否登录状态下，不管是否单行本或是单独一话(超过十页一话的)，后半部分顺序都会错乱，就以排行第一的漫画为例，好像一话超过十页后面顺序就会错乱
![IMG_20240103_103701](https://github.com/niuhuan/kobi/assets/59351770/1c4a0ec2-8442-4a0d-becf-7fdf4ca2a989)

![IMG_20240103_103958](https://github.com/niuhuan/kobi/assets/59351770/cd737c7a-a124-4544-8492-4ba725363a07)

**Comment by niuhuan** [comment]
尝试修复了一下，欢迎反馈
