### ISSUE TITLE
kobi漫画ios端为什么不能直接保存到相册？

### ISSUE THREAD

**Issue by crimemax** [niuhuan/kobi#6]
尊敬的开发者：
您好！首先很感谢您开发了这样一款支持ios端的漫画app。我手机里已经下载了pikapika和kobi和wax。我发现在pikapika阅读漫画中，长按屏幕会保存图片，点击保存图片后会自动添加到手机相册中。这对于在漫画阅读中的名场面来说至关重要，但是在kobi中有同样的功能，但此时图片不能保存到相册中，扔提示保存成功，这个给我带来了许多的困扰。已经查阅了设置中的权限两者都拥有添加新照片的权限，请问下这是正常的吗......
另外，wax这个app我找不到原网站注册，可以小小的告诉我一下下吗......
       打扰您了很抱歉！

**Comment by niuhuan** [comment]
在“文件”app中查看

**Comment by niuhuan** [comment]
我不知道是bug还是保存到了文件、保存到相册需要压缩、也许应该区分这些场景
